### PR TITLE
Add support for `chrome-devtools://` protocol

### LINKED ISSUE #18: Enhancement: Open chrome devtools links `chrome-devtools://`
Would be very convenient to be able to open debug links (`node --inspect ...`, schema `chrome-devtools`).

### PR DESCRIPTION
**Pull request by wesbos**
The current regex doesn't pick up on the dash in the protocol and doesn't highlight the links. Fixes #18

### CODE REVIEW

**Comment by wesbos** [comment]
Anyone able to merge this?

**Comment by greggb** [comment]
@wesbos You mentioned on Twitter this didn't work. I haven't been able to debug it yet, but it works fine if I remove the ipRegex matching.

Some examples:
- Current regex: http://www.regexr.com/3f1m0
- Without ipRegex: http://www.regexr.com/3f1lt
- Using Gruber's regex (modified to allow nothing after protocol): http://www.regexr.com/3f1m3

**Comment by wesbos** [comment]
@greggb Yes exactly - are you able to submit a PR with this fix?

**Comment by greggb** [comment]
@wesbos I don't want to break the IP matching. I'll PR once I find a fix.

**Comment by wesbos** [comment]
👌 thanks for your help

**Comment by dbo** [comment]
@wesbos @greggb I just checked back, but issue #18 is still not fixed, can anybody re-open it?

**Comment by greggb** [comment]
I think the correct solution is to either swap out the regex being used here or special case things like `chrome-devtools://`. I think the project owner would want to make that call, and I already have an open PR for a different feature that's been sitting for a few weeks.

Here's an interesting resource for a replacement regex https://mathiasbynens.be/demo/url-regex

Not sure if @wesbos is still tracking this, but I can't find info on usage of `chrome-devtools://` so I haven't been able to write a regex test for it. I'm going with the assumption it just replaces `http` and has additional text like a host and path.

**Comment by greggb** [comment]
Should probably ping @nkzawa so this can get some eyeballs 👀

**Comment by nkzawa** [comment]
@greggb reopened, thanks for the ping. I don't get why it doesn't work, but PR is welcome 😄

**Pull request merged**
