### PR TITLE
Open in user's browser in default

### PR DESCRIPTION
**Pull request by Hazealign**
Thanks for the nice project.
When I open link without hold Command Key, it couldn't move back. (#2)

So I fixed it to open in user's browser in default.

### CODE REVIEW

**Comment by nkzawa** [comment]
Thanks for your PR! but we're going to add an option of this behaviour in `~/.hyperterm.js`, rather than just opening url in user's browser.

@rauchg: it seems almost all people want it open in browser ? at least, we can make it default IMO.

**Comment by Hazealign** [comment]
@nkzawa That will be more great option. 👍  I'll close this PR. Thanks :)

**Comment by capaj** [comment]
@nkzawa please do make it default. It will solve the bug #2 and it conforms to the behaviour every terminal user on the planet is used to.

**Comment by vors** [comment]
+1 for changing the default.

It was not very intuitive to use `Ctrl+C` to close embedded view and I found myself closing the HyperTerm instead. It could be improved with

* supporting more hotkeys to close it (i.e. `Esc`)
* Adding a UI X element to close it. This one may be seen as "making hyperterm a browser", which is probably a non-goal.

**Pull request closed without merging**
